const model=@import("model");const workspace=@import("workspace_view");
pub const Action=enum{new_workspace,new_shell,launch_command,activate_command,select_tab,next_tab,previous_tab,reorder_tab,rename_tab,rename_current,close_tab,remove_tab,remove_current,relaunch_tab,relaunch_current,focus_signal,dismiss_notification,open_signal_inbox,retry_signals,open_integration_health,retry_dismissal,open_vscode,pin_workspace,unpin_workspace,reorder_pin,retry_service,refresh_service,connection_details,show_labels,show_repositories,toggle_current_pin,move_current_pin_up,move_current_pin_down};
pub const ActionSpec=struct{name:[]const u8,accelerator:?[]const u8,requires_ready:bool};
pub const actions=[_]ActionSpec{.{.name="win.new-workspace",.accelerator="<Primary><Shift>n",.requires_ready=true},.{.name="win.new-shell",.accelerator="<Primary><Shift>t",.requires_ready=true},.{.name="win.launch-command",.accelerator="<Primary><Shift>p",.requires_ready=true},.{.name="win.activate-command",.accelerator=null,.requires_ready=true},.{.name="win.select-tab",.accelerator=null,.requires_ready=false},.{.name="win.next-tab",.accelerator="<Primary>Page_Down",.requires_ready=false},.{.name="win.previous-tab",.accelerator="<Primary>Page_Up",.requires_ready=false},.{.name="win.reorder-tab",.accelerator=null,.requires_ready=false},.{.name="win.rename-tab",.accelerator=null,.requires_ready=false},.{.name="win.rename-current",.accelerator=null,.requires_ready=false},.{.name="win.close-tab",.accelerator="<Primary><Shift>w",.requires_ready=false},.{.name="win.remove-tab",.accelerator=null,.requires_ready=false},.{.name="win.remove-current",.accelerator=null,.requires_ready=false},.{.name="win.relaunch-tab",.accelerator=null,.requires_ready=true},.{.name="win.relaunch-current",.accelerator=null,.requires_ready=true},.{.name="win.focus-signal",.accelerator=null,.requires_ready=false},.{.name="win.dismiss-notification",.accelerator=null,.requires_ready=true},.{.name="win.open-signal-inbox",.accelerator=null,.requires_ready=false},.{.name="win.retry-signals",.accelerator=null,.requires_ready=false},.{.name="win.open-integration-health",.accelerator=null,.requires_ready=false},.{.name="win.retry-dismissal",.accelerator=null,.requires_ready=true},.{.name="win.open-vscode",.accelerator=null,.requires_ready=true},.{.name="win.pin-workspace",.accelerator=null,.requires_ready=false},.{.name="win.unpin-workspace",.accelerator=null,.requires_ready=false},.{.name="win.reorder-pin",.accelerator=null,.requires_ready=false},.{.name="win.retry-service",.accelerator=null,.requires_ready=false},.{.name="win.refresh-service",.accelerator=null,.requires_ready=false},.{.name="win.connection-details",.accelerator=null,.requires_ready=false},.{.name="win.show-labels",.accelerator=null,.requires_ready=false},.{.name="win.show-repositories",.accelerator=null,.requires_ready=false},.{.name="win.toggle-current-pin",.accelerator="<Alt>p",.requires_ready=false},.{.name="win.move-current-pin-up",.accelerator="<Alt><Shift>Up",.requires_ready=false},.{.name="win.move-current-pin-down",.accelerator="<Alt><Shift>Down",.requires_ready=false}};
pub fn enabled(state:*const model.State,spec:ActionSpec)bool{return !spec.requires_ready or state.connection==.ready;}
pub fn page(state:*model.State)workspace.Page{return (workspace.View{.state=state}).page();}
pub const Breakpoint=struct{sidebar_collapsed_below:i32=720,wide_content_above:i32=1080,pub fn collapsed(self:@This(),width:i32)bool{return width<self.sidebar_collapsed_below;}pub fn wide(self:@This(),width:i32)bool{return width>=self.wide_content_above;}};
pub const Spacing=struct{pub const inline_control:i32=4;pub const row:i32=6;pub const section:i32=12;pub const content:i32=18;};
pub const IntegrationInvocation=struct{argv:[5][]const u8,len:usize};
pub fn vscodeInvocation(state:*const model.State,pair:model.PairKey,executable:[]const u8)!IntegrationInvocation{
    for(state.workspaces[0..state.workspace_count])|*ws|if(model.PairKey.eql(.{.workspace_id=ws.id,.repository_id=pair.repository_id},pair)){
        if(ws.name_len==0)return error.MissingWorkspaceName;
        return .{.argv=.{executable,"integration","vscode","open",ws.name[0..ws.name_len]},.len=5};
    };
    return error.UnknownWorkspace;
}
