/** @jsxImportSource @opentui/solid */
import { describe, test, expect, mock, afterAll } from "bun:test"
import { makeTmpDir, cleanup, write } from "../../helpers"

// Config isolation — set BEFORE any import that touches paths.ts
const configDir = makeTmpDir("integ-tabs")
process.env.GIT_STACKS_CONFIG_DIR = configDir

// Seed YAML fixtures before any imports that read config
write(configDir, "workspaces/test-ws.yml", `name: test-ws
branch: feature/test
created: "2026-01-15T00:00:00.000Z"
repos: []
`)

write(configDir, "registry.yml", `- name: my-repo
  local_path: /tmp/integ-test-repo
  type: other
  default_branch: main
`)

write(configDir, "templates/my-tmpl.yml", `name: my-tmpl
repos:
  - repo: my-repo
    mode: worktree
`)

write(configDir, "config.yml", `workspace_root: /tmp/integ-ws-root
`)

// Mock git operations before App import
mock.module("../../../src/lib/git", () => ({
  createWorktree: mock(async () => {}),
  fetchOrigin: mock(async () => {}),
  removeWorktree: mock(async () => {}),
  isWorktreeRegistered: mock(async () => false),
  getWorktreeStatus: mock(async () => ({ dirty: false, ahead: 0, behind: 0 })),
  getCommitsBehind: mock(async () => 0),
}))

mock.module("../../../src/lib/workspace-ops", () => ({
  openWorkspace: mock(async () => {}),
  cleanWorkspace: mock(async () => ({ ok: true })),
  removeWorkspace: mock(async () => ({ ok: true })),
  mergeWorkspace: mock(async () => ({ ok: true })),
  renameWorkspace: mock(async () => {}),
  syncWorkspace: mock(async () => ({ ok: true, results: [] })),
  getWorkspaceStatus: mock(async () => []),
  editWorkspaceYaml: mock(() => ({ path: "/tmp/fake.yml", validate: () => ({ ok: true }) })),
}))

// Dynamic import after env is set and fixtures written
const { testRender } = await import("@opentui/solid")
const { default: App } = await import("../../../src/tui/dashboard/App")

const renderOpts = { kittyKeyboard: true }

describe("integration: tab switching", () => {
  test("starts on Workspaces tab showing workspace entry", async () => {
    const { renderOnce, captureCharFrame } = await testRender(
      () => <App />, renderOpts
    )
    await renderOnce()
    const frame = captureCharFrame()
    expect(frame).toContain("test-ws")
    expect(frame).toContain("feature/test")
  })

  test("pressing 2 switches to Templates tab", async () => {
    const { mockInput, renderOnce, captureCharFrame } = await testRender(
      () => <App />, renderOpts
    )
    await renderOnce()
    mockInput.pressKey("2")
    await renderOnce()
    const frame = captureCharFrame()
    expect(frame).toContain("my-tmpl")
  })

  test("pressing 3 switches to Repos tab", async () => {
    const { mockInput, renderOnce, captureCharFrame } = await testRender(
      () => <App />, renderOpts
    )
    await renderOnce()
    mockInput.pressKey("3")
    await renderOnce()
    const frame = captureCharFrame()
    expect(frame).toContain("my-repo")
  })

  test("help bar fits within 80 columns", async () => {
    const { renderOnce, captureCharFrame } = await testRender(
      () => <App />, { kittyKeyboard: true, width: 80, height: 30 }
    )
    // Render multiple times to allow async status loading to complete
    await renderOnce()
    await renderOnce()
    await renderOnce()
    const frame = captureCharFrame()
    // At 80 columns, the 1/2/3 Tabs shortcut is shown but Navigate (>=100) is not
    // The help bar string generated by App.tsx at w=80 starts with: "1/2/3 Tabs  r Refresh  ..."
    expect(frame).toContain("1/2/3 Tabs")
    expect(frame).toContain("r Refresh")
    // Navigate shortcut only appears at >= 100 columns
    expect(frame).not.toContain("Navigate")
  })

  test("workspace row shows relative age not ISO date", async () => {
    const { renderOnce, captureCharFrame } = await testRender(
      () => <App />, renderOpts
    )
    await renderOnce()
    const frame = captureCharFrame()
    // The workspace created date is 2026-01-15, which is ~65+ days ago from 2026-03-21
    // formatAge in WorkspaceRow will display it as "Nd" (days format) in the list pane
    // WorkspaceRow renders: `  ${formatAge(ws().created)}` when no messages
    expect(frame).toMatch(/\d+d/)
    // The list row should show the relative age - not the full ISO string in list pane
    // (WorkspaceDetail may show full ISO date in detail pane which is outside test scope)
    // Assert that the list pane row for test-ws contains a relative age, not raw date
    const lines = frame.split("\n")
    const wsLine = lines.find(l => l.includes("test-ws") && l.includes("feature/test"))
    expect(wsLine).toBeDefined()
    expect(wsLine).not.toContain("2026-01-15T")
    expect(wsLine).toMatch(/\d+d/)
  })
})

afterAll(() => cleanup(configDir))
